apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  labels:
    app.kubernetes.io/name: kbsconfig
    app.kubernetes.io/instance: kbsconfig-sample
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trustee-operator
  name: kbsconfig-sample
  namespace: trustee-operator-system
spec:
  kbsConfigMapName: kbs-config-grpc
  kbsAsConfigMapName: as-config-grpc
  kbsRvpsConfigMapName: rvps-config-grpc
  kbsAuthSecretName: kbs-auth-public-key
  kbsServiceType: ClusterIP
  #kbsServiceType: NodePort
  #kbsServiceType: LoadBalancer
  #kbsServiceType: ExternalName
  kbsDeploymentType: MicroservicesDeployment
  #kbsHttpsKeySecretName: kbs-https-key
  #kbsHttpsCertSecretName: kbs-https-certificate
