## Append samples you want in your CSV to this file as resources ##
namespace: kbs-operator-system
generatorOptions:
  disableNameSuffixHash: true

# uncomment to generate secrets for kbs authorization
#secretGenerator:
#- name: kbs-auth-public-key
#  files:
#  - kbs.pem
#- name: kbs-client
#  files:
#  - privateKey

# uncomment the following lines for injecting sample resources in kbs
#- literals:
#  - key1=res1val1
#  - key2=res1val2
#  name: kbsres1

patches:
- path: patch-ref-values.yaml
- path: patch-resource-policy.yaml
- path: patch-tdx-config.yaml
- path: patch-ita-config.yaml
# uncomment the following line for injecting sample resources in kbs
#- path: patch-kbs-resources.yaml

resources:
- kbsconfig_sample.yaml
- kbs-config.yaml
- as-config.yaml
- rvps-config.yaml
- rvps-reference-values.yaml
- resource-policy.yaml
- tdx-config.yaml
- ita-config.yaml
- ibmse-pv.yaml
- ibmse-pvc.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
